/**
 * Common types for the RegIntel domain model (Phase 1: The Spine)
 *
 * These types are used across all domain entities to ensure consistency
 * and type safety throughout the regulatory reasoning graph.
 */

// Identifiers (tenant-scoped)
export type TenantId = string;
export type UserId = string;
export type ProviderId = string;
export type FacilityId = string;
export type RegulationId = string;
export type PolicyId = string;
export type LinkId = string;
export type SnapshotId = string;
export type FindingId = string;
export type EvidenceId = string;
export type ActionId = string;

// Timestamps (ISO 8601)
export type ISOTimestamp = string;

/**
 * Provider Regulatory State (PRS)
 * Lifecycle-aware context that affects inspection rigor and severity scoring.
 */
export enum ProviderRegulatoryState {
  NEW_PROVIDER = 'NEW_PROVIDER',
  ESTABLISHED = 'ESTABLISHED',
  SPECIAL_MEASURES = 'SPECIAL_MEASURES',
  ENFORCEMENT_ACTION = 'ENFORCEMENT_ACTION',
  RATING_INADEQUATE = 'RATING_INADEQUATE',
  RATING_REQUIRES_IMPROVEMENT = 'RATING_REQUIRES_IMPROVEMENT',
  REOPENED_SERVICE = 'REOPENED_SERVICE',
  MERGED_SERVICE = 'MERGED_SERVICE',
}

/**
 * Domain types (CQC and IMMIGRATION must be explicitly enabled)
 */
export enum Domain {
  CQC = 'CQC',
  IMMIGRATION = 'IMMIGRATION',
}

/**
 * Origin of an inspection finding
 * SYSTEM_MOCK = generated by mock inspection engine
 * ACTUAL_INSPECTION = from real CQC inspection report
 * SELF_IDENTIFIED = provider self-identified issue
 */
export enum FindingOrigin {
  SYSTEM_MOCK = 'SYSTEM_MOCK',
  ACTUAL_INSPECTION = 'ACTUAL_INSPECTION',
  SELF_IDENTIFIED = 'SELF_IDENTIFIED',
}

/**
 * Reporting domain for findings
 * REGULATORY_HISTORY = authoritative regulatory record
 * MOCK_SIMULATION = mock inspection output (never appears in regulatory exports)
 */
export enum ReportingDomain {
  REGULATORY_HISTORY = 'REGULATORY_HISTORY',
  MOCK_SIMULATION = 'MOCK_SIMULATION',
}

/**
 * Severity levels for findings
 */
export enum Severity {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
  INFO = 'INFO',
}

/**
 * Action status lifecycle
 */
export enum ActionStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  VERIFIED_CLOSED = 'VERIFIED_CLOSED',
  REJECTED = 'REJECTED',
}

/**
 * Hash type for content addressing and integrity verification
 */
export type ContentHash = string; // SHA-256 hex string (64 chars)

/**
 * Version number for versioned entities
 */
export type VersionNumber = number; // Positive integer, starts at 1
