/**
 * Action Plan Templates
 *
 * Defines structured remediation actions for each inspection topic.
 * Templates are auto-applied when a finding is generated from a mock inspection.
 *
 * Each template entry maps a topicId → array of ActionItemTemplate.
 * Templates are content, not logic — update when CQC guidance changes.
 */

export interface ActionItemTemplate {
  title: string;
  description: string;
  category: 'POLICY' | 'EVIDENCE' | 'TRAINING' | 'PROCESS' | 'DOCUMENTATION';
  priority: 'HIGH' | 'MEDIUM' | 'LOW';
  defaultOwner: string;
  defaultDueDays: number;
}

export const ACTION_PLAN_TEMPLATES: Record<string, ActionItemTemplate[]> = {

  // ─── SAFE ────────────────────────────────────────────────────────────────────

  'safe-care-treatment': [
    {
      title: 'Upload risk assessment policy',
      description: 'Your risk assessment policy showing the most recent review date, responsible owner, and the template staff use for individual risk assessments.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide 3 completed individual risk assessments',
      description: 'Three recent, person-centred risk assessments (redacted) demonstrating they are reviewed regularly and linked to care planning.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence incident reporting and learning',
      description: 'Your incident log for the last 6 months and evidence that lessons learned are shared with the team — meeting minutes or briefing memos.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide most recent safety audit report',
      description: 'Your last internal safety audit with findings, actions taken, and sign-off confirming completion.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'safeguarding': [
    {
      title: 'Upload current safeguarding policy',
      description: 'Your safeguarding adults policy showing the most recent review date, alignment with local authority procedures, and named policy owner.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide staff safeguarding training records',
      description: 'Training certificates or matrix showing all staff have completed safeguarding adults training within the last 12 months, including new starter induction records.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Document most recent safeguarding referral',
      description: 'A redacted copy of your most recent safeguarding referral — the concern raised, timeline, agencies notified, and outcome. Proves your process works in practice.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence DoLS authorisation tracking',
      description: 'Your DoLS tracker showing all current authorisations, their status, expiry dates, and renewal application dates.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Upload supervision records evidencing safeguarding discussions',
      description: 'Recent supervision records (last 3 months) showing safeguarding is a standing agenda item discussed with each staff member.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Supervisor',
      defaultDueDays: 28,
    },
  ],

  'medication-management': [
    {
      title: 'Upload medicines management policy',
      description: 'Your medicines policy covering storage, administration, ordering, disposal, and controlled drugs procedures — with the most recent review date.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide most recent medicines audit',
      description: 'Your last medicines audit report showing findings, any discrepancies identified, actions taken, and sign-off by the responsible person.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Senior Carer',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence staff medicines competency assessments',
      description: 'Competency assessment records for all staff who administer medicines, showing assessment date and assessor sign-off.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide sample MAR chart with notes',
      description: 'A redacted Medication Administration Record (MAR) from the last month, annotated to show how gaps and PRN records are managed.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Senior Carer',
      defaultDueDays: 21,
    },
  ],

  'infection-prevention-control': [
    {
      title: 'Upload IPC policy',
      description: 'Your infection prevention and control policy with most recent review date and named lead.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide most recent IPC audit',
      description: 'Your last IPC audit report including findings, actions taken, and evidence that the environment meets required standards.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence staff IPC training',
      description: 'Training records showing all staff have completed IPC training (including hand hygiene and PPE use) within the last 12 months.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Upload cleaning schedules and completion logs',
      description: 'Current cleaning schedules with completed daily/weekly logs for the last month showing who cleaned, what was cleaned, and sign-off.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Senior Carer',
      defaultDueDays: 21,
    },
  ],

  'risk-assessment': [
    {
      title: 'Upload risk assessment policy and blank template',
      description: 'Your risk assessment policy and the blank template staff use, showing the review cycle and responsible person.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide 3 completed risk assessments',
      description: 'Three recent risk assessments (redacted) demonstrating they are person-centred, reviewed regularly, and acted upon by staff.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 14,
    },
    {
      title: 'Document escalation pathway for high-risk situations',
      description: 'A written procedure or process map showing the escalation pathway when a risk assessment identifies a significant or increasing risk.',
      category: 'PROCESS',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence environmental risk assessments',
      description: 'Completed environmental risk assessments for all communal areas and high-risk locations, with review dates visible.',
      category: 'DOCUMENTATION',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'premises-equipment': [
    {
      title: 'Upload statutory compliance certificates',
      description: 'Current gas safety certificate, electrical installation condition report (EICR), fire risk assessment, and lift inspection certificates if applicable.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide equipment maintenance schedules and logs',
      description: 'Servicing and inspection schedules for all critical care equipment (hoists, pressure mattresses, call systems) with completion records.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Upload most recent premises audit report',
      description: 'Your last premises audit showing findings, remedial actions taken, and sign-off confirming completion.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Document premises maintenance process',
      description: 'A written procedure for how maintenance requests are raised, tracked, prioritised, and signed off — including emergency repairs.',
      category: 'PROCESS',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'deprivation-of-liberty': [
    {
      title: 'Upload MCA and DoLS policy',
      description: 'Your Mental Capacity Act and Deprivation of Liberty Safeguards policy with most recent review date and named lead.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide DoLS authorisation tracker',
      description: 'Your current DoLS tracker showing all authorisations in place, their status, Standard or Urgent pathway, expiry dates, and any renewal applications.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence staff MCA training',
      description: 'Training records showing all care staff have completed Mental Capacity Act training within the last 12 months.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide sample mental capacity assessment',
      description: 'A redacted mental capacity assessment demonstrating the two-stage test is correctly applied and documented.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 21,
    },
    {
      title: 'Document Best Interest decision process',
      description: 'A redacted example of a Best Interest meeting or decision, showing who was involved and how the decision was reached.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  // ─── EFFECTIVE ───────────────────────────────────────────────────────────────

  'person-centred-care': [
    {
      title: 'Upload person-centred care policy',
      description: 'Your person-centred care policy with most recent review date, covering how individual preferences, wishes, and histories inform care planning.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide 3 sample care plans',
      description: 'Three recent, person-centred care plans (redacted) demonstrating they reflect individual needs, preferences, and goals rather than service routines.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence care plan review process',
      description: 'Records showing care plans are reviewed regularly and when needs change, with sign-off by the person, their representative, or a key worker.',
      category: 'PROCESS',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'consent': [
    {
      title: 'Upload consent policy',
      description: 'Your consent to care and treatment policy covering verbal, written, and implied consent, and what to do when consent cannot be given.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence staff consent training',
      description: 'Training records showing all care staff understand how to obtain and record consent — including for people who lack capacity.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide sample consent documentation',
      description: 'Redacted examples of consent records from care plans, showing how consent is obtained, recorded, and reviewed over time.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 21,
    },
  ],

  'nutrition-hydration': [
    {
      title: 'Upload nutrition and hydration policy',
      description: 'Your nutrition and hydration policy covering meal planning, dietary needs, MUST screening, and hydration monitoring.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence MUST screening records',
      description: 'Completed MUST (Malnutrition Universal Screening Tool) records for all residents, with most recent dates and any follow-up actions.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 14,
    },
    {
      title: 'Provide sample food and fluid intake records',
      description: 'Redacted food and fluid intake charts for 2-3 residents at risk, showing how monitoring is conducted and acted upon.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Senior Carer',
      defaultDueDays: 21,
    },
    {
      title: 'Evidence referral to dietitian or SALT',
      description: 'Records of referrals to a dietitian or Speech and Language Therapist where indicated, and outcomes of those referrals.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'staff-training-development': [
    {
      title: 'Upload training matrix for all staff',
      description: 'A training matrix showing every member of staff, what mandatory training they have completed, dates, and renewal due dates.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 7,
    },
    {
      title: 'Provide training policy and schedule',
      description: 'Your staff training and development policy with the mandatory training schedule, renewal cycles, and process for tracking compliance.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence induction records for new starters',
      description: 'Completed induction records for any staff who joined in the last 12 months, showing they completed mandatory training before working unsupervised.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Training Lead',
      defaultDueDays: 21,
    },
    {
      title: 'Upload sample training certificates',
      description: 'Sample certificates for key mandatory training areas — safeguarding, first aid, moving and handling, fire safety — to verify training quality.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Training Lead',
      defaultDueDays: 28,
    },
  ],

  'supervision-appraisal': [
    {
      title: 'Upload supervision policy',
      description: 'Your supervision and appraisal policy with minimum frequency requirements, template, and recording expectations.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide supervision schedule and completion records',
      description: 'A log showing when supervision sessions were scheduled and completed for each staff member in the last 6 months.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide sample supervision records',
      description: 'Redacted supervision notes from 2-3 recent sessions showing discussions covered wellbeing, development needs, and safeguarding.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Supervisor',
      defaultDueDays: 21,
    },
    {
      title: 'Evidence annual appraisal completion',
      description: 'Records confirming all staff have had an annual appraisal in the last 12 months with objectives set and development discussed.',
      category: 'DOCUMENTATION',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'mental-capacity-act': [
    {
      title: 'Upload MCA policy',
      description: 'Your Mental Capacity Act policy with most recent review date, covering the two-stage test, Best Interest decisions, and when to involve an IMCA.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence staff MCA training',
      description: 'Training records showing all care staff have completed MCA training within the last 12 months.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide sample capacity assessments',
      description: 'Redacted examples of mental capacity assessments showing the two-stage test correctly applied, with assessor sign-off.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 21,
    },
    {
      title: 'Document IMCA referral process',
      description: 'Written procedure for when and how to refer to an Independent Mental Capacity Advocate, with evidence of at least one recent referral.',
      category: 'PROCESS',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  // ─── CARING ──────────────────────────────────────────────────────────────────

  'dignity-respect': [
    {
      title: 'Upload dignity and respect policy',
      description: 'Your dignity and respect policy explaining how it is embedded in day-to-day care, not just policy text.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence dignity and respect training',
      description: 'Training records showing all staff have completed dignity and respect training, including how to maintain privacy during personal care.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide observation or spot-check records',
      description: 'Records from care observations or spot checks that evidence staff are treating people with dignity in practice.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Evidence feedback from people using the service',
      description: 'Satisfaction survey results, compliments received, or feedback from residents and families about how they are treated.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'service-user-involvement': [
    {
      title: 'Upload service user involvement policy',
      description: 'Your policy on involving people in decisions about their care, service development, and governance.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence residents or service user meetings',
      description: 'Minutes from at least the last 3 residents\' meetings or forums showing topics discussed and any actions taken as a result.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide feedback mechanism evidence',
      description: 'Evidence of how you collect and respond to feedback — surveys, suggestion boxes, or informal mechanisms — and an example of feedback leading to a change.',
      category: 'PROCESS',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'emotional-social-wellbeing': [
    {
      title: 'Upload emotional wellbeing and activities policy',
      description: 'Your policy on supporting emotional, social, and cultural wellbeing, including how activities are planned around individual preferences.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide activity programme records',
      description: 'Recent activity schedules and completion logs showing a range of activities offering choice, and evidence that preferences are recorded in care plans.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Activities Coordinator',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence of individual social history records',
      description: 'Sample care plans (redacted) showing how individual interests, routines, relationships, and cultural background inform daily support.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 21,
    },
  ],

  'end-of-life-care': [
    {
      title: 'Upload end of life care policy',
      description: 'Your end of life care policy covering Advance Care Planning, preferred place of death, anticipatory prescribing, and DNACPR processes.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence staff end of life care training',
      description: 'Training records showing staff have completed end of life care training, including Gold Standards Framework or equivalent.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide sample Advance Care Plans',
      description: 'Redacted examples of completed Advance Care Plans showing individual wishes, DNACPR decisions, and family communication.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 21,
    },
    {
      title: 'Evidence partnership with palliative care team',
      description: 'Records of referrals to or joint working with the local palliative care or hospice team, showing continuity of care.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  // ─── RESPONSIVE ──────────────────────────────────────────────────────────────

  'complaints-handling': [
    {
      title: 'Upload complaints policy',
      description: 'Your complaints policy and procedure showing timescales for acknowledgement and response, escalation pathway, and the CQC\'s role.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide complaints log for last 12 months',
      description: 'Your complaints register for the last 12 months showing each complaint, date received, how it was handled, timescale, and outcome.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence learning from complaints',
      description: 'Records showing at least one example where a complaint led to a change in practice — meeting minutes, a policy update, or a staff briefing.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Provide sample complaint response letters',
      description: 'Two redacted complaint response letters showing the investigation process, findings, and outcome communicated to the complainant.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'care-planning-review': [
    {
      title: 'Upload care planning policy',
      description: 'Your care planning policy covering assessment on admission, how plans are written, minimum review frequency, and who signs off changes.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide 3 recently reviewed care plans',
      description: 'Three redacted care plans with visible review dates, showing plans are current, person-centred, and co-signed by the individual or their representative.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence care plan audit',
      description: 'Your most recent care plan audit showing completeness, accuracy, and that care plans reflect current needs. Include actions taken to address any gaps.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'meeting-individual-needs': [
    {
      title: 'Upload policy on meeting individual needs',
      description: 'Your policy on how the service adapts its approach to meet individual, cultural, and personal needs.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence of individualised support planning',
      description: 'Sample care plans or support records (redacted) showing how support is tailored to personal preferences, routines, and life histories.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 14,
    },
    {
      title: 'Provide evidence of reasonable adjustments',
      description: 'Records of reasonable adjustments made for people with protected characteristics — including communication formats, religious observance, or dietary requirements.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'transitions-discharge': [
    {
      title: 'Upload transitions and discharge policy',
      description: 'Your policy for managing transitions into and out of the service, including planned discharge and emergency transfers.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence hospital discharge coordination',
      description: 'Records of a recent hospital discharge or transfer — the information shared, handover documentation, and how continuity of care was maintained.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Provide admission assessment process documentation',
      description: 'Your pre-admission assessment process and a sample completed assessment showing how you determine if the service can meet a person\'s needs.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 21,
    },
  ],

  'equality-diversity': [
    {
      title: 'Upload equality and diversity policy',
      description: 'Your equality and diversity policy referencing the Equality Act 2010, the nine protected characteristics, and how the service acts on this.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence equality and diversity training',
      description: 'Training records showing all staff have completed equality and diversity training within the last 12 months.',
      category: 'TRAINING',
      priority: 'HIGH',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide evidence of inclusive practice',
      description: 'Examples of how the service has accommodated individual cultural, religious, or personal preferences — including food, religious observance, or communication needs.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  // ─── WELL-LED ────────────────────────────────────────────────────────────────

  'governance-oversight': [
    {
      title: 'Upload governance framework document',
      description: 'Your governance policy or framework showing the management structure, lines of accountability, and how quality and safety are monitored.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide recent governance or management meeting minutes',
      description: 'Minutes from the last 3 management or governance meetings showing oversight of quality, safety, compliance, and finance.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence registered manager oversight mechanisms',
      description: 'Records of how the registered manager monitors the service — dashboards, weekly reports, walkrounds, or governance trackers.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Upload organisational chart',
      description: 'A current organisational chart showing reporting lines from frontline staff through to the registered manager and provider board.',
      category: 'DOCUMENTATION',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'quality-assurance': [
    {
      title: 'Upload quality assurance policy',
      description: 'Your quality assurance and continuous improvement policy covering how audits are planned, conducted, and acted upon.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide annual quality audit schedule and results',
      description: 'Your audit schedule for the year and completed results from at least 3 audits in the last 6 months, with action plans.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence of a completed quality improvement cycle',
      description: 'One example of an audit that identified a gap, led to an action plan, was re-audited, and showed measurable improvement.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Provide service development plan',
      description: 'Your current service improvement or development plan showing strategic priorities, named leads, and timescales.',
      category: 'DOCUMENTATION',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'staff-recruitment': [
    {
      title: 'Upload safer recruitment policy',
      description: 'Your safer recruitment policy referencing DBS checking, reference requirements, identity verification, and right to work checks.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide sample completed staff file',
      description: 'A redacted sample staff file for a recent hire showing all pre-employment checks were completed before they started work.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence DBS renewal tracking',
      description: 'Your DBS tracking log showing all staff, their DBS level, date of check, and renewal due dates. Highlight any overdue renewals.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide reference request and response templates',
      description: 'Your standard reference request template and evidence that references are obtained and reviewed before employment starts.',
      category: 'PROCESS',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'fit-proper-persons': [
    {
      title: 'Upload fit and proper person policy',
      description: 'Your policy on fit and proper person requirements for registered managers and directors, including the checks conducted.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide fit and proper person declaration',
      description: 'A completed fit and proper person declaration for the registered manager and any directors with evidence of the assessment process.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence ongoing fitness to manage',
      description: 'Records of how the provider assesses ongoing fitness — annual declarations, disclosure of change of circumstances, and DBS renewal for managers.',
      category: 'PROCESS',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'whistleblowing-openness': [
    {
      title: 'Upload whistleblowing policy',
      description: 'Your whistleblowing (speak up) policy with clear pathways for raising concerns, named contacts, and assurance of non-retaliation.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Upload duty of candour policy',
      description: 'Your statutory duty of candour policy covering when it applies, the process for notifying people of notifiable safety incidents, and the written apology.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence staff awareness of speak-up routes',
      description: 'Records showing staff have been trained on and understand the whistleblowing policy — team meeting notes, training records, or staff survey results.',
      category: 'TRAINING',
      priority: 'MEDIUM',
      defaultOwner: 'Training Lead',
      defaultDueDays: 14,
    },
    {
      title: 'Provide a duty of candour example',
      description: 'A redacted record of a duty of candour notification — the incident, who was informed, the apology provided, and any improvement actions.',
      category: 'EVIDENCE',
      priority: 'LOW',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 28,
    },
  ],

  'notifications-cqc': [
    {
      title: 'Upload notifications policy',
      description: 'Your policy on CQC statutory notifications covering which events must be notified, the timescales, and who is responsible.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide notifications log for last 12 months',
      description: 'Your register of CQC notifications made in the last 12 months including event type, date of incident, and date notified.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence notification decision-making process',
      description: 'A flowchart or written procedure showing how staff identify notifiable events and who makes the decision to notify CQC.',
      category: 'PROCESS',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'financial-sustainability': [
    {
      title: 'Upload financial governance policy',
      description: 'Your financial governance or business continuity policy showing how financial viability is monitored and what contingency plans exist.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide evidence of financial oversight',
      description: 'Board or management accounts from the last quarter showing financial oversight at governance level — not full accounts, just evidence of scrutiny.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Document business continuity plan',
      description: 'A written business continuity plan covering what happens if the service faces a critical financial, staffing, or operational crisis.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'records-management': [
    {
      title: 'Upload records management and data protection policy',
      description: 'Your records management policy covering retention periods, secure storage, access control, and GDPR compliance — with most recent review date.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence records audit',
      description: 'Your most recent records audit showing accuracy, completeness, and accessibility of care records.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide data protection and information governance training records',
      description: 'Training records showing all staff who handle personal data have completed GDPR and information governance training.',
      category: 'TRAINING',
      priority: 'MEDIUM',
      defaultOwner: 'Training Lead',
      defaultDueDays: 21,
    },
  ],

  'staff-wellbeing': [
    {
      title: 'Upload staff wellbeing policy',
      description: 'Your staff wellbeing policy covering mental health support, occupational health access, and what support is available during difficult periods.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence staff wellbeing initiatives',
      description: 'Records of wellbeing activities, staff survey results, or health promotion initiatives from the last 6 months.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Provide absence management records',
      description: 'Your absence management log and return-to-work records, showing patterns are monitored and staff receive support on return.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'learning-from-incidents': [
    {
      title: 'Upload incident reporting and learning policy',
      description: 'Your incident reporting policy covering what must be reported, the timescale for reporting, investigation process, and how learning is shared.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide incident log for last 6 months',
      description: 'Your incident register for the last 6 months showing type of incident, date, severity, investigation completed, and outcome.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence that learning is shared with staff',
      description: 'Meeting minutes, briefing notes, or staff communications showing that lessons from incidents are shared with the whole team, not just those involved.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide a serious incident investigation report',
      description: 'A redacted investigation report for one serious incident in the last 12 months, showing root cause analysis and systemic changes made.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],

  'partnership-working': [
    {
      title: 'Upload partnership working policy',
      description: 'Your policy on working with external agencies — NHS, local authority, community services — covering referral processes and information sharing.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Evidence multi-disciplinary team (MDT) involvement',
      description: 'Records of MDT meetings or referrals in the last 3 months — GP visits, occupational therapy, community nursing — showing integrated care.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide referral log for external services',
      description: 'Your referral register showing referrals made to external services in the last 6 months, outcomes, and follow-up actions.',
      category: 'DOCUMENTATION',
      priority: 'LOW',
      defaultOwner: 'Care Coordinator',
      defaultDueDays: 28,
    },
  ],

  'staffing': [
    {
      title: 'Upload staffing policy and dependency tool',
      description: 'Your staffing policy covering minimum staffing levels, how dependency is assessed, and the tool or calculation used to set rotas.',
      category: 'POLICY',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 7,
    },
    {
      title: 'Provide completed rota for last 4 weeks',
      description: 'Completed rotas for the last 4 weeks showing planned vs actual staffing levels, any shortfalls, and how they were covered.',
      category: 'EVIDENCE',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Evidence dependency assessment records',
      description: 'Dependency assessment records showing how current staffing levels are matched to the needs of the people the service supports.',
      category: 'DOCUMENTATION',
      priority: 'HIGH',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 14,
    },
    {
      title: 'Provide agency usage log if applicable',
      description: 'If agency staff are used, provide a log showing frequency, which roles were covered, briefing records, and what steps are in place to reduce reliance.',
      category: 'DOCUMENTATION',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
    {
      title: 'Upload skills matrix',
      description: 'A skills matrix showing the qualifications, competencies, and specialist skills of all staff on each shift, confirming appropriate skill mix is maintained.',
      category: 'EVIDENCE',
      priority: 'MEDIUM',
      defaultOwner: 'Registered Manager',
      defaultDueDays: 21,
    },
  ],
};
